# Basic site info
title:              "İsa ALP •••"
description:        "I want a beautiful life."
keywords:           "isa,alp,isa alp,hello"
logo_text:          "İsa ALP"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              "/assets/logo.png" # site image cover

# Site URL settings
url:                http://isaalp.com # main url
baseurl:            null # for gh-pages
enforce_ssl:        isaalp.com

# Site author info
author:
  name:             "Heiswayi Nrird"
  email:            isa@isaalp.com
  github_username:  alp
  twitter_username: alp
  facebook_url:     https://www.facebook.com

# Disqus comment settings
disqus_enabled:     false
disqus_shortname:   1111

# GA
google_analytics_code: 

# Build settings
source:             ./
destination:        ./_site
permalink:          /:title
markdown:           kramdown
highlighter:        rouge
timezone:           Asia/Kuala_Lumpur
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

gems:
  - jekyll-sitemap
